apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: {{ .Values.name }}
spec:
  amiFamily: {{ .Values.amiFamily }}
  blockDeviceMappings:
    - {{ if eq .Values.amiFamily "Ubuntu" }}
      deviceName: /dev/sda1
      {{ else }}
      deviceName: /dev/xvda
      {{ end }}
      ebs:
        volumeSize: 200Gi # Big disk for Notebook instances
        volumeType: gp3
        encrypted: true
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    cat <<-EOF > /etc/profile.d/bootstrap.sh
    #!/bin/sh

    # Configure NVMe volumes in RAID0 configuration
    # https://github.com/awslabs/amazon-eks-ami/blob/056e31f8c7477e893424abce468cb32bbcd1f079/files/bootstrap.sh#L35C121-L35C126
    # Mount will be: /mnt/k8s-disks
    export LOCAL_DISKS='raid0'
    EOF

    # Source extra environment variables in bootstrap script
    sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh

    --BOUNDARY--
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelector:
    Name: {{ .Values.clusterName }}-private*  # Name of the Subnets to spin up the nodes
  securityGroupSelector:                      # required, when not using launchTemplate
    Name: {{ .Values.clusterName }}-node*     # Name of the SecurityGroup to be used with Nodes
  tags:
    InstanceType: {{ .Values.name }}
